<script setup>
import { computed, onMounted, ref } from 'vue';
import { Filter, Search, SlidersHorizontal } from 'lucide-vue-next';
import { useRoute } from 'vue-router';
import { productService } from '../services/productService';
import ProductCard from '../components/ProductCard.vue';
const route = useRoute(); const products = ref([]); const categories = ref([]); const loading = ref(true); const error = ref(''); const search = ref(route.query.q || ''); const category = ref(route.query.category || ''); const sort = ref('latest'); const emit = defineEmits(['notify']);
const filtered = computed(() => { let list = [...products.value]; const query = search.value.toLowerCase(); if (query) list = list.filter(p => `${p.name} ${p.description || ''} ${p.category_name || ''}`.toLowerCase().includes(query)); if (category.value) list = list.filter(p => String(p.category_id) === String(category.value)); if (sort.value === 'price-low') list.sort((a,b) => a.price - b.price); if (sort.value === 'price-high') list.sort((a,b) => b.price - a.price); return list; });
onMounted(async () => { try { const [p, c] = await Promise.all([productService.list(), productService.categories()]); products.value = p.data; categories.value = c.data; } catch { error.value = 'Unable to load products.'; } finally { loading.value = false; } });
</script>
<template><section class="page-heading"><div class="container"><p class="kicker">THE COLLECTION</p><h1>Hardware for the long haul.</h1><p>Thoughtful specs. Honest pricing. No filler.</p></div></section><section class="container catalog-layout"><aside class="filters"><div class="filter-title"><SlidersHorizontal :size="17" /> Filter catalog</div><label class="field-label">Search<input v-model="search" placeholder="Search products"><Search :size="16" /></label><label class="field-label">Category<select v-model="category"><option value="">All categories</option><option v-for="item in categories" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></aside><div class="catalog-content"><div class="catalog-toolbar"><span><b>{{ filtered.length }}</b> products</span><label>Sort <select v-model="sort"><option value="latest">Latest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div><div v-if="loading" class="product-grid"><div v-for="n in 6" :key="n" class="skeleton-card"></div></div><p v-else-if="error" class="state error-state">{{ error }}</p><div v-else-if="!filtered.length" class="state"><Filter :size="30" /><h3>No products match that search.</h3><p>Try a different keyword or clear your filters.</p></div><div v-else class="product-grid"><ProductCard v-for="product in filtered" :key="product.id" :product="product" @notify="emit('notify', $event)" /></div></div></section></template>
