// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVjWzYQIeaeuLmpmWXDF_kwz5iYXzG0to',
    appId: '1:859650448420:web:938bbac7c1f93ba07e0cb1',
    messagingSenderId: '859650448420',
    projectId: 'computerstore-8ce80',
    authDomain: 'computerstore-8ce80.firebaseapp.com',
    storageBucket: 'computerstore-8ce80.firebasestorage.app',
    measurementId: 'G-N80Y75TSY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKB2b8dqSzvVkgelB_JiEMSeh50v9FTI',
    appId: '1:859650448420:android:6342a51d061754267e0cb1',
    messagingSenderId: '859650448420',
    projectId: 'computerstore-8ce80',
    storageBucket: 'computerstore-8ce80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Q2ixREUrVqCdPt7gcHTXsLGhQ8dLCXg',
    appId: '1:859650448420:ios:1bce16eaef29b6967e0cb1',
    messagingSenderId: '859650448420',
    projectId: 'computerstore-8ce80',
    storageBucket: 'computerstore-8ce80.firebasestorage.app',
    iosBundleId: 'com.example.flutterStoreUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Q2ixREUrVqCdPt7gcHTXsLGhQ8dLCXg',
    appId: '1:859650448420:ios:1bce16eaef29b6967e0cb1',
    messagingSenderId: '859650448420',
    projectId: 'computerstore-8ce80',
    storageBucket: 'computerstore-8ce80.firebasestorage.app',
    iosBundleId: 'com.example.flutterStoreUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVjWzYQIeaeuLmpmWXDF_kwz5iYXzG0to',
    appId: '1:859650448420:web:5924e5652d83898f7e0cb1',
    messagingSenderId: '859650448420',
    projectId: 'computerstore-8ce80',
    authDomain: 'computerstore-8ce80.firebaseapp.com',
    storageBucket: 'computerstore-8ce80.firebasestorage.app',
    measurementId: 'G-2PX590DPCZ',
  );
}
